### ISSUE TITLE
You've forgotten "recursive"

### ISSUE THREAD

**Issue by olivierpons** [summerstyle/jsonTreeViewer#9]
Your expand function wasn't 100% working. Here's a working version of your expand Tree function:
```javascript
        /**
         * Expands all tree nodes (objects or arrays) recursively
         *
         * @param {Function | undefined} filterFunc - 'true' if this node should be expanded
         * @param {Object | undefined} node - starting node if precised
         */
        expand : function(filterFunc, node) {
            var self = this,
                n = (typeof(node) === 'undefined' ? this.rootNode : node);
            if (!n.isComplex) {
                return;
            }
            if (typeof(filterFunc) === 'function') {
                if (filterFunc(n)) {
                    n.expand();
                    n.childNodes.forEach(function(item) {
                        self.expand(filterFunc, item);
                    });
                } else {
                    n.collapse();
                }
            } else {
                n.expand();
                n.childNodes.forEach(function(item) {
                    self.expand(filterFunc, item);
                });
            }
        },
```

**Comment by summerstyle** [comment]
Now, expanding of tree is expanding of all tree, recursively, or expanding of **first level** of descendants by some function. Also, I will add expanding by some depth.

This is not expanding recursively by filter function at all depth (now). 
For this each node has own expanding method and I will add feature with expanding by some conditions (filter function).

Thank you for your idea, I have added this feature in TODO list.

**Comment by olivierpons** [comment]
Ok this suggestion was because maybe the documentation was unclear about that (no offense).

In all tree + nodes existing libraries (), you have the functions I've suggested (maybe another naming convention).

Thanks for your library it's great!

**Comment by summerstyle** [comment]
And I will fix it in documentation)
